import { test, expect } from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';
const sample = JSON.parse(fs.readFileSync('public/sample-pack/requirements.json', 'utf8'));
const json = (value: unknown) => ({ name: 'requirements.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(value)) });
function pdf(pages: number) {
 const objects = ['<< /Type /Catalog /Pages 2 0 R >>', `<< /Type /Pages /Count ${pages} /Kids [${Array.from({length:pages}, (_,i)=>`${i+3} 0 R`).join(' ')}] >>`, ...Array.from({length:pages}, ()=>'<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << >> >>')];
 let body = '%PDF-1.4\n'; const offsets = [0];
 objects.forEach((object, index) => { offsets.push(Buffer.byteLength(body)); body += `${index + 1} 0 obj\n${object}\nendobj\n`; });
 const start = Buffer.byteLength(body); body += `xref\n0 ${objects.length+1}\n0000000000 65535 f \n${offsets.slice(1).map(offset => `${String(offset).padStart(10,'0')} 00000 n \n`).join('')}trailer\n<< /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${start}\n%%EOF`;
 return Buffer.from(body);
}
test('imports, validation, page counts, removal and limits', async ({ page }) => {
 const runtimeErrors: string[] = []; page.on('pageerror', error => runtimeErrors.push(error.message));
 await page.goto('/');
 await expect(page.getByRole('button', { name: 'Generate package' })).toBeDisabled();
 await page.getByLabel('Import requirements JSON').setInputFiles(path.resolve('public/sample-pack/requirements.json'));
 await expect(page.getByText(sample.tender.tender_id, { exact:true })).toBeVisible();
 await expect(page.locator('.requirements li')).toHaveCount(sample.requirements.length);
 await expect(page.locator('.status.missing')).toHaveCount(sample.requirements.filter((r: {mandatory:boolean}) => r.mandatory).length);
 const different = { tender: { ...sample.tender, tender_id: 'OTHER-100', title: 'Office furniture procurement' }, requirements: [{ ...sample.requirements[0], id:'b', order:9, title_en:'Second document'}, { ...sample.requirements[1], id:'a', order:2, title_en:'First document', mandatory:false }] };
 await page.getByLabel('Import requirements JSON').setInputFiles(json(different));
 await expect(page.locator('.requirements li').first()).toContainText('First document');
 await expect(page.getByText('OTHER-100', {exact:true})).toBeVisible();
 await page.getByLabel('Import requirements JSON').setInputFiles({name:'bad.json', mimeType:'application/json', buffer:Buffer.from('{bad')});
 await expect(page.getByRole('alert')).toContainText('not valid JSON');
 await expect(page.getByText('OTHER-100', {exact:true})).toBeVisible();
 await page.getByLabel('Import requirements JSON').setInputFiles(json({ tender: {}, requirements: [] }));
 await expect(page.getByRole('alert')).toContainText('tender.tender_id');
 await page.getByLabel('Import requirements JSON').setInputFiles(json({...different,tender:{...different.tender,submission_deadline:'2026-02-30'}}));
 await expect(page.getByRole('alert')).toContainText('real date');
 await page.getByRole('button', {name:'Dismiss messages'}).click();
 await page.getByLabel('Upload PDF documents').setInputFiles([{name:'three-pages.pdf', mimeType:'application/pdf', buffer:pdf(3)}, {name:'notes.txt',mimeType:'text/plain',buffer:Buffer.from('text')}, {name:'broken.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-broken')}]);
 await expect(page.locator('.file-row').filter({hasText:'three-pages.pdf'})).toContainText('3 pages');
 await expect(page.getByRole('alert')).toContainText('Only PDF');
 await expect(page.locator('.file-error')).toContainText('Cannot read this PDF');
 await page.getByRole('button',{name:'Remove three-pages.pdf',exact:true}).click();
 await expect(page.locator('.file-row').filter({hasText:'three-pages.pdf'})).toHaveCount(0);
 await page.getByRole('button',{name:'Remove broken.pdf',exact:true}).click();
 await page.getByRole('button',{name:'Dismiss messages'}).click();
 await page.getByLabel('Upload PDF documents').setInputFiles(Array.from({length:31},(_,i)=>({name:`file-${i}.pdf`,mimeType:'application/pdf',buffer:pdf(1)})));
 await expect(page.locator('.file-row')).toHaveCount(30);
 await expect(page.getByRole('alert')).toContainText('limit is 30');
 await expect(page.locator('.file-row').last()).toContainText('1 page', {timeout:30000});
 while (await page.getByRole('button',{name:/^Remove /}).count()) await page.getByRole('button',{name:/^Remove /}).first().click();
 await page.getByRole('button',{name:'Dismiss messages'}).click();
 fs.mkdirSync('../../work/fixtures', {recursive:true});
 fs.writeFileSync('../../work/fixtures/too-large.pdf', Buffer.alloc(50*1024*1024+1));
 await page.getByLabel('Upload PDF documents').setInputFiles(path.resolve('../../work/fixtures/too-large.pdf'));
 await expect(page.getByRole('alert')).toContainText('50 MB total');
 await expect(page.locator('.file-row')).toHaveCount(0);
 fs.writeFileSync('../../work/fixtures/large-a.pdf', Buffer.concat([pdf(1),Buffer.alloc(26*1024*1024)]));
 fs.copyFileSync('../../work/fixtures/large-a.pdf','../../work/fixtures/large-b.pdf');
 await page.getByRole('button',{name:'Dismiss messages'}).click();
 await page.getByLabel('Upload PDF documents').setInputFiles(['large-a.pdf','large-b.pdf'].map(name=>path.resolve('../../work/fixtures', name)));
 await expect(page.locator('.file-row')).toHaveCount(1);
 await expect(page.getByRole('alert')).toContainText('large-b.pdf');
 await expect(page.getByRole('alert')).toContainText('50 MB total');
 await page.getByRole('button',{name:'Remove large-a.pdf',exact:true}).click();
 await page.getByRole('button',{name:'Load sample',exact:true}).click();
 const filenames = fs.readdirSync('public/sample-pack/documents').filter(name => name.endsWith('.pdf'));
 await expect(page.locator('.file-row')).toHaveCount(filenames.length);
 await expect(page.getByRole('status')).toContainText('Sample loaded');
 for (const name of filenames) await expect(page.locator('.file-row').filter({hasText:name}).first()).toContainText(/\d+ pages?/);
 await page.setViewportSize({width:1440,height:1000});
 await page.screenshot({path:'../../work/desktop.png',fullPage:true});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth)).toBe(true);
 await page.setViewportSize({width:375,height:812});
 await page.screenshot({path:'../../work/mobile.png',fullPage:true});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth)).toBe(true);
 await page.setViewportSize({width:320,height:740});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth)).toBe(true);
 expect(runtimeErrors).toEqual([]);
});
