import { test, expect, type Page } from '@playwright/test';
import fs from 'node:fs';
import path from 'node:path';
const sample = JSON.parse(fs.readFileSync('public/sample-pack/requirements.json', 'utf8'));
const row = (page: Page, title: string) => page.locator('.requirements li').filter({has:page.getByRole('heading',{name:title,exact:true})});
async function match(page: Page, title: string, filename: string) {
 const select = page.getByLabel(`PDF for ${title}`,{exact:true});
 const option = select.locator('option').filter({hasText:filename}).first();
 await expect(option).toBeEnabled();
 await select.selectOption(await option.getAttribute('value') ?? '');
}
test('sample matching, duplicates, expiry, replacement, undo and removal', async ({page}) => {
 const errors:string[]=[]; page.on('pageerror',error=>errors.push(error.message));
 await page.goto('/'); await page.getByRole('button',{name:'Load sample',exact:true}).click();
 await expect(page.getByRole('status')).toContainText('Sample loaded');
 const experience = row(page,'Experience Certificate');
 const copy = page.locator('.file-row').filter({hasText:'experience_cert (1).pdf'}).first();
 await expect(copy.locator('.duplicate-note')).toContainText('Identical bytes');
 await match(page,'Experience Certificate','experience_cert (1).pdf');
 await expect(experience.locator('.status')).toHaveText('OK');
 const otherSelect = page.getByLabel('PDF for Audited Financial Statement',{exact:true});
 await expect(otherSelect.locator('option').filter({hasText:'experience_cert.pdf'})).toBeDisabled();
 await expect(otherSelect.locator('option').filter({hasText:'experience_cert (1).pdf'})).toBeDisabled();
 await expect(page.getByLabel('PDF for Trade License',{exact:true}).locator('option').filter({hasText:'experience_cert (1).pdf'})).toBeDisabled();
 await page.getByRole('button',{name:'Unmatch Experience Certificate',exact:true}).click();
 await expect(experience.locator('.status')).toHaveText('Missing');
 await page.getByRole('button',{name:'Undo last match change',exact:true}).click();
 await expect(experience.locator('.status')).toHaveText('OK');
 await page.getByRole('button',{name:'Remove experience_cert (1).pdf',exact:true}).click();
 await expect(experience.locator('.status')).toHaveText('Missing');
 await expect(page.getByRole('button',{name:'Undo last match change'})).toBeDisabled();
 await match(page,'Audited Financial Statement','experience_cert.pdf');
 await expect(row(page,'Audited Financial Statement').locator('.status')).toHaveText('OK');
 await page.getByRole('button',{name:'Unmatch Audited Financial Statement',exact:true}).click();
 await expect(row(page,'Audited Financial Statement').locator('.status')).toHaveText('Not provided');
 await match(page,'Trade License','trade_license_2025.pdf');
 const license = row(page,'Trade License');
 const expiry = page.getByLabel('Expiry date for Trade License',{exact:true});
 await expect(license.locator('.status')).toHaveText('Expiry date needed');
 await expiry.fill('2025-12-31'); await expect(license.locator('.status')).toHaveText('Expired');
 await expect(license.locator('.blocker-reason')).toContainText('before the submission deadline');
 await match(page,'Trade License','trade_license_2026.pdf');
 await expect(expiry).toHaveValue('');
 await expect(license.locator('.status')).toHaveText('Expiry date needed');
 await page.getByRole('button',{name:'Undo last match change',exact:true}).click();
 await expect(expiry).toHaveValue('2025-12-31');
 await expect(license.locator('.status')).toHaveText('Expired');
 await match(page,'Trade License','trade_license_2026.pdf');
 await expiry.fill('2026-12-31'); await expect(license.locator('.status')).toHaveText('OK');
 await expiry.fill(sample.tender.submission_deadline); await expect(license.locator('.status')).toHaveText('OK');
 await expiry.fill(''); await expect(license.locator('.status')).toHaveText('Expiry date needed');
 await expiry.fill(sample.tender.submission_deadline);
 await page.getByRole('button',{name:'Remove trade_license_2026.pdf',exact:true}).click();
 await expect(license.locator('.status')).toHaveText('Missing'); await expect(expiry).toHaveCount(0);
 await expect(row(page,"Manufacturer's Authorization").locator('.status')).toHaveText('Not provided');
 await match(page,"Manufacturer's Authorization",'bank_solvency.pdf');
 const optional = row(page,"Manufacturer's Authorization");
 const optionalDate = page.getByLabel("Expiry date for Manufacturer's Authorization",{exact:true});
 await expect(optional.locator('.status')).toHaveText('Expiry date needed');
 await optionalDate.fill('2026-10-19'); await expect(optional.locator('.status')).toHaveText('Expired');
 await optionalDate.fill(sample.tender.submission_deadline); await expect(optional.locator('.status')).toHaveText('OK');
 await page.getByRole('button',{name:"Unmatch Manufacturer's Authorization",exact:true}).click();
 await expect(optional.locator('.status')).toHaveText('Not provided');
 await expect(page.getByRole('button',{name:'Generate package',exact:true})).toBeDisabled();
 expect(await page.locator('.requirements li').count()).toBe(await page.locator('.requirements .status').count());
 await page.setViewportSize({width:1440,height:1000}); await page.screenshot({path:'../../work/review-desktop.png',fullPage:true});
 for (const width of [375,320]) { await page.setViewportSize({width,height:812}); expect(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth)).toBe(true); }
 await page.screenshot({path:'../../work/review-mobile.png',fullPage:true});
 expect(errors).toEqual([]);
});
test('different dataset, same names with different bytes, readiness and import reset', async ({page}) => {
 await page.goto('/');
 const different = {tender:{...sample.tender,tender_id:'NEW-22',submission_deadline:'2028-02-29'},requirements:[{id:'__proto__',order:2,title_en:'Insurance document with a long descriptive title',title_bn:'ক',mandatory:false,has_expiry:true},{id:'a',order:1,title_en:'Business registration',title_bn:'খ',mandatory:true,has_expiry:false}]};
 const load = async () => page.getByLabel('Import requirements JSON').setInputFiles({name:'new.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(different))});
 await load();
 await page.getByLabel('Upload PDF documents').setInputFiles(['03_tin_certificate.pdf','04_vat_certificate.pdf'].map(name=>path.resolve('public/sample-pack/documents',name)));
 await match(page,'Business registration','03_tin_certificate.pdf');
 await expect(page.locator('.readiness-counts')).toContainText('1 OK · 1 optional not provided · 0 blocking issues');
 await match(page,different.requirements[0].title_en,'04_vat_certificate.pdf');
 await expect(page.locator('.readiness-counts')).toContainText('1 blocking issue');
 await page.getByLabel(`Expiry date for ${different.requirements[0].title_en}`,{exact:true}).fill('2028-02-29');
 await expect(page.locator('.readiness-counts')).toContainText('2 OK');
 await expect(page.getByRole('button',{name:'Generate package',exact:true})).toBeDisabled();
 await page.setViewportSize({width:320,height:812}); expect(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth)).toBe(true);
 await load(); await expect(row(page,'Business registration').locator('.status')).toHaveText('Missing');
 await expect(row(page,different.requirements[0].title_en).locator('.status')).toHaveText('Not provided');
 await expect(page.getByRole('button',{name:'Undo last match change'})).toBeDisabled();
 const original = fs.readFileSync('public/sample-pack/documents/03_tin_certificate.pdf');
 const changed = fs.readFileSync('public/sample-pack/documents/04_vat_certificate.pdf');
 await page.getByLabel('Upload PDF documents').setInputFiles([{name:'same.pdf',mimeType:'application/pdf',buffer:original},{name:'same.pdf',mimeType:'application/pdf',buffer:changed}]);
 const sameName = page.locator('.file-row').filter({has:page.locator('strong').filter({hasText:/^same\.pdf$/})});
 await expect(sameName).toHaveCount(2);
 // Different bytes share a name, while each remains a copy of its source PDF.
 await expect(sameName.first().locator('.duplicate-note')).toContainText('03_tin_certificate.pdf');
 await expect(sameName.last().locator('.duplicate-note')).toContainText('04_vat_certificate.pdf');
 await match(page,'Business registration','03_tin_certificate.pdf');
 await expect(page.getByLabel(`PDF for ${different.requirements[0].title_en}`,{exact:true}).locator('option').filter({hasText:'same.pdf'}).first()).toBeDisabled();
 await expect(page.getByLabel(`PDF for ${different.requirements[0].title_en}`,{exact:true}).locator('option').filter({hasText:'same.pdf'}).last()).toBeEnabled();
 // Undo a later match without discarding an expiry edit in another row.
 await match(page,different.requirements[0].title_en,'04_vat_certificate.pdf');
 await page.getByLabel(`Expiry date for ${different.requirements[0].title_en}`,{exact:true}).fill('2028-02-29');
 await page.getByRole('button',{name:'Unmatch Business registration',exact:true}).click();
 await page.getByLabel(`Expiry date for ${different.requirements[0].title_en}`,{exact:true}).fill('2028-03-01');
 await page.getByRole('button',{name:'Undo last match change',exact:true}).click();
 await expect(page.getByLabel(`Expiry date for ${different.requirements[0].title_en}`,{exact:true})).toHaveValue('2028-03-01');
});
