import { en, type Strings } from './strings';
export const bn: Strings = {
 brand:'টেন্ডারডেস্ক', product:'দরপত্রের নথি প্যাকেজ প্রস্তুতকারক', local:'ফাইল এই ডিভাইসেই থাকে', eyebrow:'আপনার দরপত্রের কর্মক্ষেত্র', stepTag:'আমদানি · যাচাই · তৈরি', footer:'টেন্ডারডেস্ক · সুশৃঙ্খল নথি, আত্মবিশ্বাসী জমা।', browser:'সব কাজ ব্রাউজারেই হয়',
 mandatoryMissing:count=>`${count}টি বাধ্যতামূলক নথি অনুপস্থিত`, fileUsage:(count,max)=>`${count} / ${max}টি ফাইল`, fileDetails:(pages,size)=>`${pages} পৃষ্ঠা · ${size}`, pagesRead:(pages,reading)=>`${pages} পৃষ্ঠা পড়া হয়েছে${reading?' · বাকি ফাইল পড়া হচ্ছে…':''}`,
 heading:'সম্পূর্ণ দরপত্রের শুরু এখানেই।', intro:'প্রয়োজনীয় নথির তালিকা ও সহায়ক PDF যোগ করুন। যাচাই করে জমা দেওয়ার উপযোগী প্যাকেজ তৈরি করুন।', import:'প্রয়োজনীয় নথির তালিকা আমদানি', sample:'নমুনা লোড করুন', importing:'লোড হচ্ছে…',
 step1:'আমদানি',step2:'মিল ও যাচাই',step3:'তৈরি',later:'আগে তালিকার যাচাই শেষ করুন', summary:'দরপত্রের বিবরণ',emptyTitle:'আপনার পরের দরপত্র, সুশৃঙ্খলভাবে।',emptySummary:'দরপত্রের বিবরণ ও প্রয়োজনীয় নথি দেখতে requirements.json আমদানি করুন।', entity:'ক্রয়কারী প্রতিষ্ঠান',bidder:'দরদাতা',deadline:'জমা দেওয়ার শেষ তারিখ',
 docs:'সহায়ক নথি',docsHelp:'দরপত্রে অন্তর্ভুক্ত করতে চান এমন PDF যোগ করুন।',choose:'PDF বাছাই করুন',drop:'PDF এখানে ছেড়ে দিন',dropHelp:'অথবা ডিভাইস থেকে ফাইল বাছাই করুন',limits:'শুধু PDF · সর্বোচ্চ ৩০টি ফাইল · মোট ৫০ MB',noDocs:'এখনও কোনো নথি যোগ হয়নি',noDocsHelp:'ফাইলের নাম ও প্রকৃত পৃষ্ঠাসংখ্যা এখানে দেখা যাবে।',reading:'পৃষ্ঠা পড়া হচ্ছে…',remove:'সরান',
 requirements:'প্রয়োজনীয় নথির তালিকা',reqHelp:'দরপত্রে নির্ধারিত ক্রমে সাজানো।',reqEmpty:'প্রয়োজনীয় নথির তালিকা দিয়ে শুরু করুন',reqEmptyHelp:'requirements.json বাছাই করুন অথবা নমুনা লোড করে কর্মক্ষেত্র দেখুন।',mandatory:'বাধ্যতামূলক',optional:'ঐচ্ছিক',expiry:'মেয়াদ শেষের তারিখ প্রয়োজন',noExpiry:'মেয়াদ শেষের তারিখ প্রয়োজন নেই',missing:'অনুপস্থিত',notProvided:'দেওয়া হয়নি',order:'ক্রম',document:'প্রয়োজনীয় নথি',status:'অবস্থা',
 readiness:'প্যাকেজের প্রস্তুতি',generate:'প্যাকেজ তৈরি করুন',blocked:'প্যাকেজ তৈরির আগে উপরের বাধাগুলো সমাধান করুন।',next:'প্যাকেজ তৈরির আগে প্রতিটি মিল যাচাই করুন',nextHelp:'প্রতি নথির জন্য একটি PDF। একই ফাইলের অনুলিপি একবারই ব্যবহার করা যাবে।',sampleNotice:'নমুনা লোড হয়েছে। নমুনার সব প্রতিষ্ঠান ও নথি কাল্পনিক।',expiryNeeded:'মেয়াদের তারিখ প্রয়োজন',expired:'মেয়াদোত্তীর্ণ',ok:'ঠিক আছে',chooseMatch:'একটি PDF বাছাই করুন…',unmatch:'মিল বাতিল',undo:'শেষ মিল পরিবর্তন ফেরান',expiryDate:'মেয়াদ শেষের তারিখ',checking:'ফাইল যাচাই হচ্ছে…',duplicate:'একই ফাইলের অনুলিপি',hashFail:'ফাইলের অনুলিপি যাচাই করা যায়নি। সরিয়ে আবার যোগ করুন।',
 matchLabel:title=>`${title}-এর PDF`,expiryLabel:title=>`${title}-এর মেয়াদ শেষের তারিখ`,unmatchLabel:title=>`${title}-এর মিল বাতিল`,duplicateOf:names=>`একই ফাইলের অনুলিপি: ${names}। একটি কপি ব্যবহার করুন।`,assignedTo:title=>`মিল করা হয়েছে: ${title}`,used:'ইতিমধ্যে মিল করা হয়েছে',unavailable:'ফাইল পড়া যায়নি অথবা যাচাই চলছে',conflict:'এই PDF বা তার অনুলিপি ইতিমধ্যে মিল করা হয়েছে। আগে সেই মিল বাতিল করুন।',
 reasons:{missing:'এই বাধ্যতামূলক নথির জন্য একটি PDF বাছাই করুন।',expiryNeeded:'মিল করা PDF-এর বৈধ মেয়াদ শেষের তারিখ লিখুন।',expired:'জমা দেওয়ার শেষ তারিখের আগে মেয়াদ শেষ। PDF বদলান অথবা তারিখ সংশোধন করুন।'},readyCounts:(ok,skipped,blockers)=>`${ok}টি ঠিক আছে · ${skipped}টি ঐচ্ছিক নথি দেওয়া হয়নি · ${blockers}টি বাধা`,uploadCounts:(checking,errors,duplicates)=>`${checking}টি ফাইল যাচাই হচ্ছে · ${errors}টি ফাইল অপাঠ্য · ${duplicates}টি অনুলিপি`,allReady:'প্যাকেজ তৈরির জন্য তালিকা প্রস্তুত।',jsonSyntax:'এটি বৈধ JSON নয়। বিন্যাস ঠিক করে আবার চেষ্টা করুন।',jsonFile:'.json প্রয়োজনীয় নথির তালিকা বাছাই করুন।',dismiss:'বার্তা বন্ধ করুন',pdfOnly:'শুধু PDF গ্রহণ করা হয়।',countLimit:'সর্বোচ্চ ৩০টি PDF। নতুন ফাইল যোগ করার আগে একটি সরান।',sizeLimit:'এই ফাইল যোগ করলে মোট ৫০ MB সীমা অতিক্রম হবে।',unreadable:'এই PDF পড়া যায়নি। ফাইল ক্ষতিগ্রস্ত বা পাসওয়ার্ড-সুরক্ষিত হতে পারে।',sampleFail:'নমুনা লোড হয়নি। আবার চেষ্টা করুন অথবা ডিভাইস থেকে ফাইল আমদানি করুন।',privacy:'আপনার নথি ব্রাউজারেই প্রক্রিয়াকরণ হয়; কোনো সার্ভারে পাঠানো হয় না।',readFail:'প্রয়োজনীয় নথির ফাইল পড়া যায়নি। অন্য ফাইল দিয়ে চেষ্টা করুন।',
 workflow:'প্যাকেজ তৈরির ধাপ',jsonInput:'প্রয়োজনীয় নথির JSON আমদানি',pdfInput:'PDF নথি যোগ করুন',language:'ইন্টারফেসের ভাষা',ready:'সব যাচাই সম্পন্ন। ক্রমানুসারে PDF প্যাকেজ তৈরি করুন।',noPack:'প্যাকেজ শুরু করতে প্রয়োজনীয় নথির তালিকা আমদানি করুন।',wait:'সব ফাইল পড়া ও অনুলিপি যাচাই শেষ হওয়া পর্যন্ত অপেক্ষা করুন।',generating:'প্যাকেজ তৈরি হচ্ছে…',success:'প্যাকেজ সফলভাবে তৈরি হয়েছে।',download:'প্যাকেজ ডাউনলোড করুন',generationError:'প্যাকেজ তৈরি হয়নি। আপনার কাজ অক্ষত আছে। আবার চেষ্টা করুন।',stale:'প্যাকেজ তৈরির সময় তথ্য বদলেছে। হালনাগাদ তালিকা দিয়ে আবার তৈরি করুন।',encrypted:'পাসওয়ার্ড-সুরক্ষিত PDF ব্যবহার করা যাবে না। আগে পাসওয়ার্ড ছাড়া কপি রপ্তানি করুন।',coverOverflow:'পাঠযোগ্য এক পৃষ্ঠার প্রচ্ছদের জন্য দরপত্রের বিবরণ অত্যন্ত দীর্ঘ। শিরোনাম ছোট করে আবার চেষ্টা করুন।',unsupported:'প্রচ্ছদে এমন অক্ষর আছে যা এই ফন্টে দেখানো যায় না। দরপত্রের বিবরণ যাচাই করুন।',footerNote:'প্রচ্ছদ ইংরেজিতে থাকবে। মূল পৃষ্ঠার অনুপাত অক্ষুণ্ণ রেখে নিচে আলাদা ফুটার যোগ হবে।',downloadName:(filename,pages)=>`${filename} · ${pages} পৃষ্ঠা`,byteUnit:'MB',fileSize:bytes=>`${(bytes/1024/1024).toFixed(1)} MB`,totalSize:bytes=>`${(bytes/1024/1024).toFixed(1)} MB / ৫০ MB`,
};
// Upload errors keep their original filenames; translate only interface fragments.
export function localizeMessage(message: string, locale: 'en'|'bn') {
 const pairs = Object.keys(en).flatMap(key => {
  const a=en[key as keyof Strings], b=bn[key as keyof Strings];
  return typeof a==='string' && typeof b==='string' ? [[a,b]] : [];
 });
 let result=message;
 for (const [a,b] of pairs.sort((a,b)=>b[1].length-a[1].length)) result=result.replaceAll(b,a);
 if(locale==='en') return result;
 for (const [a,b] of pairs.sort((a,b)=>b[0].length-a[0].length)) result=result.replaceAll(a,b);
 const fields:Record<string,string>={tender_id:'দরপত্রের আইডি',title:'শিরোনাম',procuring_entity:'ক্রয়কারী প্রতিষ্ঠান',bidder:'দরদাতা',submission_deadline:'জমা দেওয়ার শেষ তারিখ',id:'আইডি',title_en:'ইংরেজি শিরোনাম',title_bn:'বাংলা শিরোনাম',mandatory:'বাধ্যতামূলক',has_expiry:'মেয়াদ প্রযোজ্য'};
 result=result.replace(/tender\.(\w+) must be a non-empty text value\./g,(_,key)=>`${fields[key]??key} খালি রাখা যাবে না; লেখা প্রয়োজন।`)
 .replace(/Requirement (\d+): (\w+) must be non-empty text\./g,(_,n,key)=>`নথি ${n}: ${fields[key]??key} খালি রাখা যাবে না।`)
 .replace(/Requirement (\d+): (\w+) must be true or false\./g,(_,n,key)=>`নথি ${n}: ${fields[key]??key} true বা false হতে হবে।`)
 .replace(/Requirement (\d+): order must be a positive whole number\./g,(_,n)=>`নথি ${n}: ক্রম একটি ধনাত্মক পূর্ণসংখ্যা হতে হবে।`)
 .replace(/Requirement (\d+): (id|order) must be unique\./g,(_,n,key)=>`নথি ${n}: ${key==='id'?'আইডি':'ক্রম'} অন্য নথির সঙ্গে এক হতে পারবে না।`)
 .replace(/Requirement (\d+) must be an object\./g,(_,n)=>`নথি ${n} একটি JSON অবজেক্ট হতে হবে।`)
 .replace('Add a tender object containing the tender details.','দরপত্রের বিবরণসহ tender অবজেক্ট যোগ করুন।')
 .replace('requirements must be a non-empty list of documents.','requirements-এ অন্তত একটি নথি থাকতে হবে।')
 .replace('submission_deadline must be a real date in YYYY-MM-DD format.','জমা দেওয়ার শেষ তারিখ YYYY-MM-DD বিন্যাসে একটি প্রকৃত তারিখ হতে হবে।');
 return result;
}
